import random

def get_heuristic(board):
    """
    Calculate the number of attacking pairs of queens.
    A state with 0 attacks is a goal state.
    """
    n = len(board)
    attacks = 0
    for i in range(n):
        for j in range(i + 1, n):
            # Check for same row or same diagonal
            if board[i] == board[j] or abs(board[i] - board[j]) == abs(i - j):
                attacks += 1
    return attacks

def generate_random_board(n):
    """
    Generate a random initial state.
    Each column gets one queen in a random row.
    """
    return [random.randint(0, n - 1) for _ in range(n)]

def get_best_neighbor(board):
    """
    Find the neighbor with the lowest heuristic value.
    A neighbor is generated by moving a single queen in its column to another row.
    Returns the best neighbor and its heuristic value.
    """
    n = len(board)
    best_board = list(board)
    min_attacks = get_heuristic(board)
    
    for col in range(n):
        for row in range(n):
            if board[col] != row:
                # Create a neighbor by moving the queen in this column to a different row
                neighbor = list(board)
                neighbor[col] = row
                attacks = get_heuristic(neighbor)
                
                # If we find a strictly better neighbor, update the best neighbor
                if attacks < min_attacks:
                    min_attacks = attacks
                    best_board = list(neighbor)
                
    return best_board, min_attacks

def hill_climbing_n_queens(n):
    """
    Solve N-Queens using Random-Restart Hill Climbing.
    Standard hill climbing often gets stuck in local optima.
    Random restarts ensure we eventually find a global optimum (0 attacks).
    """
    restarts = 0
    while True:
        # Start with a random configuration
        board = generate_random_board(n)
        current_attacks = get_heuristic(board)
        
        # Climb until we reach a local or global optimum
        while current_attacks > 0:
            neighbor, neighbor_attacks = get_best_neighbor(board)
            if neighbor_attacks >= current_attacks:
                # We reached a local optimum (or plateau). Need to restart.
                break
            # Move to the better neighbor
            board = neighbor
            current_attacks = neighbor_attacks
            
        # If we reached the global optimum (0 attacks), we are done
        if current_attacks == 0:
            return board, restarts
            
        # Otherwise, increment restarts and try again from a new random state
        restarts += 1

def print_board(board):
    """
    Print the board configuration visually.
    Q represents a Queen, and . represents an empty space.
    """
    n = len(board)
    for row in range(n):
        row_str = ""
        for col in range(n):
            if board[col] == row:
                row_str += "Q "
            else:
                row_str += ". "
        print(row_str)

if __name__ == "__main__":
    print("=== N-Queen Problem Solver (Hill Climbing) ===")
    while True:
        try:
            n_str = input("Enter the number of queens (N): ")
            n = int(n_str)
            if n <= 0:
                print("Please enter a positive integer.")
                continue
            if n in [2, 3]:
                print(f"No solution exists for N={n}. Please try N >= 4.")
                continue
            break
        except ValueError:
            print("Invalid input. Please enter an integer.")

    print(f"\nSolving {n}-Queens problem using Random-Restart Hill Climbing...")
    solution, restarts = hill_climbing_n_queens(n)
    
    print(f"\nSolution found with {restarts} restarts!")
    print(f"Board Configuration (Index = Column, Value = Row):")
    print(solution)
    print("\nVisual Board:")
    print_board(solution)
